const products=[{id:1,name:'Kapal Api Mix 23g',category:'Kopi',price:2000},{id:2,name:'Luwak White Coffee',category:'Kopi',price:2000},{id:3,name:'Indocoffee',category:'Kopi',price:2000},{id:5,name:'Indomie Soto / Ayam Bawang',category:'Mie',price:3500},{id:6,name:'Indomie Goreng',category:'Mie',price:4000},{id:15,name:'Coca-Cola Zero Sugar',category:'Minuman',price:6000},{id:22,name:'Telur Negeri Curah',category:'Sembako',price:26000},{id:27,name:'Gula Curah',category:'Sembako',price:20000},{id:31,name:'Minyak Kita 1L',category:'Sembako',price:23000},{id:32,name:'Beras',category:'Sembako',price:15000}];
const rupiah=n=>'Rp'+Number(n).toLocaleString('id-ID');
let roleCheckInProgress=false;
function setView(loggedIn,user){const login=document.getElementById('loginView');const admin=document.getElementById('adminView');if(loggedIn){login.style.display='none';admin.style.display='flex';admin.hidden=false;document.getElementById('adminEmail').textContent=user?.email||'Admin';renderProducts()}else{admin.style.display='none';admin.hidden=true;login.style.display='grid';login.hidden=false;}}
async function checkAdminRole(user){if(!user||!user.emailVerified)return false;try{const snap=await firebaseDb.ref(`users/${user.uid}/role`).once('value');return snap.val()==='admin'}catch{return false}}
async function adminLogin(){const email=document.getElementById('email').value.trim();const password=document.getElementById('password').value;if(!email||!password)return msg('Isi email dan password.');msg('Memproses login...');try{const credential=await firebaseAuth.signInWithEmailAndPassword(email,password);await credential.user.reload();const currentUser=firebaseAuth.currentUser;if(!currentUser.emailVerified){await firebaseAuth.signOut();msg('Email admin belum diverifikasi. Cek email verifikasi terlebih dahulu.');return}const isAdmin=await checkAdminRole(currentUser);if(!isAdmin){await firebaseAuth.signOut();msg('Akun ini bukan admin. Gunakan akun admin.');return}msg('');setView(true,currentUser)}catch(e){msg(e.code==='auth/invalid-credential'?'Email atau password salah.':e.message);setView(false)}}
function msg(text){document.getElementById('loginMessage').textContent=text}
function adminLogout(){firebaseAuth.signOut()}
function showSection(id,button){document.querySelectorAll('.section').forEach(x=>x.classList.remove('active-section'));document.getElementById(id).classList.add('active-section');document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));button.classList.add('active');const names={dashboard:'Dashboard',products:'Kelola Produk',orders:'Pesanan',users:'Pengguna',laundry:'Self Laundry'};document.getElementById('pageTitle').textContent=names[id]||'Admin'}
function renderProducts(){document.getElementById('productCount').textContent=products.length;document.getElementById('productList').innerHTML=products.map(p=>`<div class="product-row"><div><b>${p.name}</b><br><small>${p.category} · ${rupiah(p.price)}</small></div><button onclick="alert('Form edit produk akan ditambahkan pada tahap berikutnya.')">Edit</button></div>`).join('')}
function addProduct(){alert('Form tambah produk akan kita sambungkan ke Firebase Database setelah struktur admin selesai.')}
setView(false);
firebaseAuth.onAuthStateChanged(async user=>{if(!user){setView(false);return}if(roleCheckInProgress)return;roleCheckInProgress=true;await user.reload();const currentUser=firebaseAuth.currentUser;const isAdmin=await checkAdminRole(currentUser);roleCheckInProgress=false;if(isAdmin){setView(true,currentUser)}else{await firebaseAuth.signOut();setView(false);msg(currentUser?.emailVerified===false?'Email admin belum diverifikasi.':'Akun ini bukan admin. Silakan login dengan akun admin.')}});