const products=[{id:1,name:'Kapal Api Mix 23g',category:'Kopi',price:2000},{id:2,name:'Luwak White Coffee',category:'Kopi',price:2000},{id:3,name:'Indocoffee',category:'Kopi',price:2000},{id:5,name:'Indomie Soto / Ayam Bawang',category:'Mie',price:3500},{id:6,name:'Indomie Goreng',category:'Mie',price:4000},{id:15,name:'Coca-Cola Zero Sugar',category:'Minuman',price:6000},{id:22,name:'Telur Negeri Curah',category:'Sembako',price:26000},{id:27,name:'Gula Curah',category:'Sembako',price:20000},{id:31,name:'Minyak Kita 1L',category:'Sembako',price:23000},{id:32,name:'Beras',category:'Sembako',price:15000}];
const rupiah=n=>'Rp'+Number(n).toLocaleString('id-ID');
function setView(loggedIn,user){const login=document.getElementById('loginView');const admin=document.getElementById('adminView');if(loggedIn){login.style.display='none';admin.style.display='flex';admin.hidden=false;document.getElementById('adminEmail').textContent=user?.email||'Admin';renderProducts()}else{admin.style.display='none';admin.hidden=true;login.style.display='grid';login.hidden=false;document.getElementById('email').value='';document.getElementById('password').value='';}}
function adminLogin(){const email=document.getElementById('email').value.trim();const password=document.getElementById('password').value;if(!email||!password)return msg('Isi email dan password.');msg('Memproses login...');firebaseAuth.signInWithEmailAndPassword(email,password).catch(e=>{msg(e.code==='auth/invalid-credential'?'Email atau password salah.':e.message);setView(false)})}
function msg(text){document.getElementById('loginMessage').textContent=text}
function adminLogout(){firebaseAuth.signOut()}
function showSection(id,button){document.querySelectorAll('.section').forEach(x=>x.classList.remove('active-section'));document.getElementById(id).classList.add('active-section');document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));button.classList.add('active');const names={dashboard:'Dashboard',products:'Kelola Produk',orders:'Pesanan',users:'Pengguna',laundry:'Self Laundry'};document.getElementById('pageTitle').textContent=names[id]||'Admin'}
function renderProducts(){document.getElementById('productCount').textContent=products.length;document.getElementById('productList').innerHTML=products.map(p=>`<div class="product-row"><div><b>${p.name}</b><br><small>${p.category} · ${rupiah(p.price)}</small></div><button onclick="alert('Form edit produk akan ditambahkan pada tahap berikutnya.')">Edit</button></div>`).join('')}
function addProduct(){alert('Form tambah produk akan kita sambungkan ke Firebase Database setelah struktur admin selesai.')}
setView(false);
firebaseAuth.onAuthStateChanged(user=>setView(!!user,user));